version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: "db_cont"
    environment:
      MYSQL_DATABASE: webshopsql
      MYSQL_USER: webshop
      MYSQL_PASSWORD: webshop
      MYSQL_ROOT_PASSWORD: webroot
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
